"""Vietnamese labels for the diagrams in diagrams.py (line-by-line lookup).

Identifiers, product names and contract events stay in English.
"""

VI = {
    'Member / business step': 'Member / business step',
    'Confirmed provider': 'Provider đã chốt',
    'Cyclone-built': 'Cyclone build',
    'Join with referral': 'Join qua referral',
    'invite, Sponsor': 'invite link, Sponsor',
    'Wallet': 'Wallet',
    'log in, own keys': 'login, tự giữ key',
    'Fund wallet': 'Fund wallet',
    'USDC, one network': 'USDC, một network',
    'deposit, redeem': 'deposit, redeem',
    'Games and Points': 'Game và Points',
    'no cash value': 'không có giá trị tiền',
    'Support': 'Support',
    'in-app chat': 'chat trong app',
    'genealogy, plan': 'genealogy, plan',
    'login, wallets': 'login, wallet',
    'USDC transfer': 'transfer USDC',
    'shares, queues': 'share, queue',
    'Cyclone game': 'Cyclone game',
    'Points service': 'Points service',
    'Helm Web App and backend (Cyclone)': 'Helm Web App và backend (Cyclone)',
    'member record · referral sync · chain indexer · reconciliation · admin and exceptions': 'member record · referral sync · chain indexer · reconciliation · admin và exception',
    'Invite link': 'Invite link',
    'Sign up, log in': 'Signup, login',
    'Wallet created': 'Tạo wallet',
    'Read vault terms': 'Đọc vault terms',
    'Deposit request': 'Deposit request',
    'Position confirmed': 'Position confirmed',
    'Play, earn Points': 'Chơi game, nhận Points',
    'Request Redemption': 'Request Redemption',
    'Browser': 'Browser',
    'Helm Web App · Privy SDK (Member signs) · Chatwoot widget': 'Helm Web App · Privy SDK (Member ký) · Chatwoot widget',
    'API and auth': 'API và auth',
    'verifies Privy tokens': 'verify Privy token',
    'Member DB and ledger': 'Member DB và ledger',
    'referrals · events · audit': 'referral · event · audit',
    'Integration workers': 'Integration worker',
    'outbox · retries': 'outbox · retry',
    'confirmations': 'confirmation',
    'Reconciliation and alerts': 'Reconciliation và alert',
    'Admin console': 'Admin console',
    'exceptions · screening cases · Sponsor corrections': 'exception · screening case · Sponsor correction',
    'genealogy': 'genealogy',
    'Game and Points': 'Game và Points',
    'Cyclone service': 'Cyclone service',
    'Sanctions API': 'Sanctions API',
    'address screening': 'address screening',
    'support': 'support',
    'conversations': 'conversation',
    'read-only': 'read-only',
    'Arbitrum: USDC · Onyx deposit and redeem queues · shares · valuation': 'Arbitrum: USDC · Onyx deposit/redeem queue · share · valuation',
    'Privy token': 'Privy token',
    'Member app': 'Member app',
    'store invite code': 'lưu invite code',
    'log in': 'login',
    'access token, embedded wallet': 'access token, embedded wallet',
    'register(token, invite code)': 'register(token, invite code)',
    'verify token, read wallet address': 'verify token, đọc wallet address',
    'member + pending Referral Request; screen address': 'tạo member, Referral Request pending; screen address',
    'find customer by Helm ID': 'find customer theo Helm ID',
    'create customer (id, externalIds, enrollerId)': 'create customer (id, externalIds, enrollerId)',
    'read node and upline': 'read node và upline',
    'Sponsor Edge accepted': 'Sponsor Edge accepted',
    'referral confirmed': 'referral confirmed',
    'Exchange or wallet': 'Exchange hoặc wallet',
    'USDC transfer to Member address': 'transfer USDC tới Member address',
    'Transfer event seen (submitted)': 'thấy Transfer event (submitted)',
    'wait N confirmations': 'chờ N confirmation',
    'funding confirmed (chain, tx, log)': 'funding confirmed (chain, tx, log)',
    'screen source address, record event': 'screen source address, ghi event',
    'balance updated': 'cập nhật balance',
    'Onyx contracts': 'Onyx contracts',
    'Vault operator': 'Vault operator',
    'accept vault terms (version)': 'accept vault terms (version)',
    'add wallet to allowlist': 'add wallet vào allowlist',
    'approve exact amount': 'approve đúng amount',
    'update valuation; execute deposit requests': 'update valuation; execute deposit request',
    'position confirmed; business event': 'position confirmed; business event',
    'position and valuation date': 'position và valuation date',
    'Game and points service': 'Game và Points service',
    'play (linked Helm member)': 'chơi (đã link Helm member)',
    'validate result, apply limits': 'validate kết quả, áp limit',
    'signed event (event id, member, Points)': 'signed event (event id, member, Points)',
    'verify signature; dedupe on event id': 'verify signature; dedupe theo event id',
    'Points balance (from service)': 'Points balance (từ service)',
    'screen destination (own wallet)': 'screen destination (wallet của Member)',
    'update valuation; ensure liquidity': 'update valuation; bảo đảm liquidity',
    'execute redeem requests': 'execute redeem request',
    'position reduced; business event': 'position giảm; business event',
    'USDC in wallet; stages complete': 'USDC về wallet; hoàn tất',
    'Agent': 'Agent',
    'request chat identity': 'request chat identity',
    'member ID + identity hash': 'member ID + identity hash',
    'open verified conversation': 'mở conversation đã verify',
    'conversation with member ID': 'conversation kèm member ID',
    'look up status (read-only)': 'tra status (read-only)',
    'ops resolves exception (approval, audit)': 'ops xử lý exception (approval, audit)',
    'reply to Member': 'reply Member',
}
